In [3]:
"""
Actions that we need to train the adapter on:
- LGTM - Accept the draft as-is
- add content
- add tool call at a specific index
- replace content
- replace tool call 
- delete tool call at a specific index
- delete content

How should we modify the data so that the adapter can perform the above actions?
- LGTM: keep data as-is
- add content: delete content when gold content is present.
- add tool call: drop tool call at random indices
- replace content: corrupt the content.
- replace tool call:
    - corrupt the tool call name at index I.
    - corrupt the tool call arguments at index I.
- delete tool call: add random tool call at random indices.
- delete content: add content to when no gold content is present.

Sometimes the adapter model can take multiple actions in a single turn. Some actions cannot be performed together.
- no other action allowed if LGTM is performed.
- you can either add content or replace content or delete content but not do them together.
- you cannot add a tool call at index I and delete a tool call at the same index I. Should do replace tool call at index I.
"""

'\nActions that we need to train the adapter on:\n- LGTM - Accept the draft as-is\n- add content\n- add tool call at a specific index\n- replace content\n- replace tool call \n- delete tool call at a specific index\n- delete content\n\nHow should we modify the data so that the adapter can perform the above actions?\n- LGTM: keep data as-is\n- add content: delete content when gold content is present.\n- add tool call: drop tool call at random indices\n- replace content: corrupt the content.\n- replace tool call:\n    - corrupt the tool call name at index I.\n    - corrupt the tool call arguments at index I.\n- delete tool call: add random tool call at random indices.\n- delete content: add content to when no gold content is present.\n\nSometimes the adapter model can take multiple actions in a single turn. Some actions cannot be performed together.\n- no other action allowed if LGTM is performed.\n- you can either add content or replace content or delete content but not do them together.\n- you cannot add a tool call at index I and delete a tool call at the same index I. Should do replace tool call at index I.\n'

In [108]:
# building training data for the adapter

import json

hermes_data_path = './data/raw/hermes_func_calling.jsonl'
hermes_data = []
with open(hermes_data_path, 'r') as f:
    for line in f:
        hermes_data.append(json.loads(line))

hermes_data[0]

{'source_dataset': 'NousResearch/hermes-function-calling-v1',
 'source_config': 'func_calling',
 'source_row_idx': 0,
 'id': '82088305-310b-45cb-ac76-ab273503b5cd',
 'conversations': [{'from': 'system',
   'value': 'You are a function calling AI model. You are provided with function signatures within <tools> </tools> XML tags. You may call one or more functions to assist with the user query. Don\'t make assumptions about what values to plug into functions.\n<tools>\n[{"type": "function", "function": {"name": "get_camera_live_feed", "description": "Retrieves the live feed from a specified security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the camera."}, "stream_quality": {"type": "string", "description": "The desired quality of the live stream.", "enum": ["720p", "1080p", "4k"]}}, "required": ["camera_id"]}}}, {"type": "function", "function": {"name": "list_all_cameras", "description": "Lists all the security cameras connected to the home network.", "parameters": {"type": "object", "properties": {"include_offline": {"type": "boolean", "description": "Whether to include cameras that are currently offline.", "default": false}}, "required": []}}}, {"type": "function", "function": {"name": "record_camera_feed", "description": "Starts recording the live feed from a specified security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the camera."}, "duration": {"type": "integer", "description": "The duration in minutes for which to record the feed.", "default": 60}}, "required": ["camera_id"]}}}, {"type": "function", "function": {"name": "get_recorded_feed", "description": "Retrieves a previously recorded feed from a specified security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the camera."}, "start_time": {"type": "string", "description": "The start time of the recording to retrieve, in ISO 8601 format."}, "end_time": {"type": "string", "description": "The end time of the recording to retrieve, in ISO 8601 format."}}, "required": ["camera_id", "start_time", "end_time"]}}}, {"type": "function", "function": {"name": "pan_tilt_camera", "description": "Controls the pan and tilt functions of a PTZ (Pan-Tilt-Zoom) security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the PTZ camera."}, "pan_angle": {"type": "integer", "description": "The angle in degrees to pan the camera. Positive values pan right, negative values pan left."}, "tilt_angle": {"type": "integer", "description": "The angle in degrees to tilt the camera. Positive values tilt up, negative values tilt down."}}, "required": ["camera_id", "pan_angle", "tilt_angle"]}}}]\n</tools>\nFor each function call return a json object with function name and arguments within <tool_call> </tool_call> tags with the following schema:\n<tool_call>\n{"name": <function-name>, "arguments": <args-dict>}\n</tool_call>\n'},
  {'from': 'human',
   'value': 'I\'ve recently installed a new security system at my home, and I want to ensure everything is functioning as it should. Specifically, I\'d like to start by checking the live feed from the camera located at the front door to monitor any activity. The camera has a unique identifier, which I\'ve already configured to be "front_door." I\'d prefer to view the live stream in high definition, so a 1080p quality would be ideal. Could you please call the appropriate function to retrieve the live feed from my front door camera in 1080p quality and provide me with the link to the stream?\n\nFollowing this, I would also like to record the live feed from this camera for the next 30 minutes. This is to test the recording feature and to keep an archived copy for security purposes. Please initiate the recording function for the "front_door" camera with a recording duration of 30 minutes.\n\nLastly, as part of my routine surveillance checks, I need to review footage from yesterday between 3 PM and 5 PM. The camera "front_garden" should have the recording for that period. I need to retrieve this specific recorded feed. The start time for the recording was at 15:00 on April 22, 2023, and it ended at 17:00 on the same day.\n\nTo summarize, I request the execution of the following functions with the provided details:\n1. Retrieve the live feed from the "front_door" camera at 1080p quality.\n2. Start a 30-minute recording of the live feed from the "front_door" camera.\n3. Retrieve the recorded feed from the "front_garden" camera, focusing on the time period between 15:00 and 17:00 on April 22, 2023.\n\nThank you for assisting with the management of my home security camera feeds.'},
  {'from': 'gpt',
   'value': '<tool_call>\n{"name": "get_camera_live_feed", "arguments": {"camera_id": "front_door", "stream_quality": "1080p"}}\n</tool_call>\n<tool_call>\n{"name": "record_camera_feed", "arguments": {"camera_id": "front_door", "duration": 30}}\n</tool_call>\n<tool_call>\n{"name": "get_recorded_feed", "arguments": {"camera_id": "front_garden", "start_time": "2023-04-22T15:00:00Z", "end_time": "2023-04-22T17:00:00Z"}}\n</tool_call>\n'},
  {'from': 'tool',
   'value': '<tool_response>\n{"name": "get_camera_live_feed", "content": {"camera_id": "front_door", "stream_quality": "1080p", "live_feed_url": "https://homecam.example.com/live/front_door_1080p"}}\n</tool_response>\n<tool_response>\n{"name": "record_camera_feed", "content": {"camera_id": "front_door", "duration": 30, "recording_status": "started", "recording_url": "https://homecam.example.com/recordings/front_door_20230423T143000Z.mp4"}}\n</tool_response>\n<tool_response>\n{"name": "get_recorded_feed", "content": {"camera_id": "front_garden", "start_time": "2023-04-22T15:00:00Z", "end_time": "2023-04-22T17:00:00Z", "recorded_feed_url": "https://homecam.example.com/recordings/front_garden_20230422T150000Z_to_20230422T170000Z.mp4"}}\n</tool_response>\n'},
  {'from': 'gpt',
   'value': 'I have successfully executed all the requested functions for your home security cameras. Here are the results:\n\n1. **Live Feed from "front_door" Camera:**\n   - You can view the high-definition 1080p live feed from your front door camera at the [following link](https://homecam.example.com/live/front_door_1080p).\n\n2. **Recording of "front_door" Camera:**\n   - The 30-minute recording of the live feed from the "front_door" camera has been started successfully. You will be able to access the recorded feed at [this link](https://homecam.example.com/recordings/front_door_20230423T143000Z.mp4) once the recording completes.\n\n3. **Retrieved Recorded Feed from "front_garden" Camera:**\n   - The requested recorded feed from the "front_garden" camera for the period between 3 PM and 5 PM on April 22, 2023, is available at the [following link](https://homecam.example.com/recordings/front_garden_20230422T150000Z_to_20230422T170000Z.mp4).\n\nPlease use the provided links to manage and review your home security camera feeds. If you require further assistance or have any more tasks related to your security system, feel free to let me know.'}],
 'tools': '[{"type": "function", "function": {"name": "get_camera_live_feed", "description": "Retrieves the live feed from a specified security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the camera."}, "stream_quality": {"type": "string", "description": "The desired quality of the live stream.", "enum": ["720p", "1080p", "4k"]}}, "required": ["camera_id"]}}}, {"type": "function", "function": {"name": "list_all_cameras", "description": "Lists all the security cameras connected to the home network.", "parameters": {"type": "object", "properties": {"include_offline": {"type": "boolean", "description": "Whether to include cameras that are currently offline.", "default": false}}, "required": []}}}, {"type": "function", "function": {"name": "record_camera_feed", "description": "Starts recording the live feed from a specified security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the camera."}, "duration": {"type": "integer", "description": "The duration in minutes for which to record the feed.", "default": 60}}, "required": ["camera_id"]}}}, {"type": "function", "function": {"name": "get_recorded_feed", "description": "Retrieves a previously recorded feed from a specified security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the camera."}, "start_time": {"type": "string", "description": "The start time of the recording to retrieve, in ISO 8601 format."}, "end_time": {"type": "string", "description": "The end time of the recording to retrieve, in ISO 8601 format."}}, "required": ["camera_id", "start_time", "end_time"]}}}, {"type": "function", "function": {"name": "pan_tilt_camera", "description": "Controls the pan and tilt functions of a PTZ (Pan-Tilt-Zoom) security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the PTZ camera."}, "pan_angle": {"type": "integer", "description": "The angle in degrees to pan the camera. Positive values pan right, negative values pan left."}, "tilt_angle": {"type": "integer", "description": "The angle in degrees to tilt the camera. Positive values tilt up, negative values tilt down."}}, "required": ["camera_id", "pan_angle", "tilt_angle"]}}}]',
 'category': 'IoT and Home Automation',
 'subcategory': 'Security Camera Management',
 'task': 'View and Manage Security Camera Feeds'}

In [109]:
# convert to messages format
from typing import Any

ROLE_MAP = {
    "system": "system",
    "human": "user",
    "gpt": "assistant",
    "tool": "tool",
}

def _coerce_message(turn: dict[str, Any]) -> dict[str, str] | None:
    from_role = turn.get("from")
    value = turn.get("value")
    if not isinstance(from_role, str) or not isinstance(value, str):
        return None

    role = ROLE_MAP.get(from_role)
    if role is None:
        return None
    return {"role": role, "content": value}

_coerce_message(hermes_data[0]['conversations'][0])

{'role': 'system',
 'content': 'You are a function calling AI model. You are provided with function signatures within <tools> </tools> XML tags. You may call one or more functions to assist with the user query. Don\'t make assumptions about what values to plug into functions.\n<tools>\n[{"type": "function", "function": {"name": "get_camera_live_feed", "description": "Retrieves the live feed from a specified security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the camera."}, "stream_quality": {"type": "string", "description": "The desired quality of the live stream.", "enum": ["720p", "1080p", "4k"]}}, "required": ["camera_id"]}}}, {"type": "function", "function": {"name": "list_all_cameras", "description": "Lists all the security cameras connected to the home network.", "parameters": {"type": "object", "properties": {"include_offline": {"type": "boolean", "description": "Whether to include cameras that are currently offline.", "default": false}}, "required": []}}}, {"type": "function", "function": {"name": "record_camera_feed", "description": "Starts recording the live feed from a specified security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the camera."}, "duration": {"type": "integer", "description": "The duration in minutes for which to record the feed.", "default": 60}}, "required": ["camera_id"]}}}, {"type": "function", "function": {"name": "get_recorded_feed", "description": "Retrieves a previously recorded feed from a specified security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the camera."}, "start_time": {"type": "string", "description": "The start time of the recording to retrieve, in ISO 8601 format."}, "end_time": {"type": "string", "description": "The end time of the recording to retrieve, in ISO 8601 format."}}, "required": ["camera_id", "start_time", "end_time"]}}}, {"type": "function", "function": {"name": "pan_tilt_camera", "description": "Controls the pan and tilt functions of a PTZ (Pan-Tilt-Zoom) security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the PTZ camera."}, "pan_angle": {"type": "integer", "description": "The angle in degrees to pan the camera. Positive values pan right, negative values pan left."}, "tilt_angle": {"type": "integer", "description": "The angle in degrees to tilt the camera. Positive values tilt up, negative values tilt down."}}, "required": ["camera_id", "pan_angle", "tilt_angle"]}}}]\n</tools>\nFor each function call return a json object with function name and arguments within <tool_call> </tool_call> tags with the following schema:\n<tool_call>\n{"name": <function-name>, "arguments": <args-dict>}\n</tool_call>\n'}

In [110]:
for example in hermes_data:
    messages = []
    for turn in example['conversations']:
        message = _coerce_message(turn)
        if message is not None:
            messages.append(message)
    example['messages'] = messages
hermes_data[0]

{'source_dataset': 'NousResearch/hermes-function-calling-v1',
 'source_config': 'func_calling',
 'source_row_idx': 0,
 'id': '82088305-310b-45cb-ac76-ab273503b5cd',
 'conversations': [{'from': 'system',
   'value': 'You are a function calling AI model. You are provided with function signatures within <tools> </tools> XML tags. You may call one or more functions to assist with the user query. Don\'t make assumptions about what values to plug into functions.\n<tools>\n[{"type": "function", "function": {"name": "get_camera_live_feed", "description": "Retrieves the live feed from a specified security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the camera."}, "stream_quality": {"type": "string", "description": "The desired quality of the live stream.", "enum": ["720p", "1080p", "4k"]}}, "required": ["camera_id"]}}}, {"type": "function", "function": {"name": "list_all_cameras", "description": "Lists all the security cameras connected to the home network.", "parameters": {"type": "object", "properties": {"include_offline": {"type": "boolean", "description": "Whether to include cameras that are currently offline.", "default": false}}, "required": []}}}, {"type": "function", "function": {"name": "record_camera_feed", "description": "Starts recording the live feed from a specified security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the camera."}, "duration": {"type": "integer", "description": "The duration in minutes for which to record the feed.", "default": 60}}, "required": ["camera_id"]}}}, {"type": "function", "function": {"name": "get_recorded_feed", "description": "Retrieves a previously recorded feed from a specified security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the camera."}, "start_time": {"type": "string", "description": "The start time of the recording to retrieve, in ISO 8601 format."}, "end_time": {"type": "string", "description": "The end time of the recording to retrieve, in ISO 8601 format."}}, "required": ["camera_id", "start_time", "end_time"]}}}, {"type": "function", "function": {"name": "pan_tilt_camera", "description": "Controls the pan and tilt functions of a PTZ (Pan-Tilt-Zoom) security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the PTZ camera."}, "pan_angle": {"type": "integer", "description": "The angle in degrees to pan the camera. Positive values pan right, negative values pan left."}, "tilt_angle": {"type": "integer", "description": "The angle in degrees to tilt the camera. Positive values tilt up, negative values tilt down."}}, "required": ["camera_id", "pan_angle", "tilt_angle"]}}}]\n</tools>\nFor each function call return a json object with function name and arguments within <tool_call> </tool_call> tags with the following schema:\n<tool_call>\n{"name": <function-name>, "arguments": <args-dict>}\n</tool_call>\n'},
  {'from': 'human',
   'value': 'I\'ve recently installed a new security system at my home, and I want to ensure everything is functioning as it should. Specifically, I\'d like to start by checking the live feed from the camera located at the front door to monitor any activity. The camera has a unique identifier, which I\'ve already configured to be "front_door." I\'d prefer to view the live stream in high definition, so a 1080p quality would be ideal. Could you please call the appropriate function to retrieve the live feed from my front door camera in 1080p quality and provide me with the link to the stream?\n\nFollowing this, I would also like to record the live feed from this camera for the next 30 minutes. This is to test the recording feature and to keep an archived copy for security purposes. Please initiate the recording function for the "front_door" camera with a recording duration of 30 minutes.\n\nLastly, as part of my routine surveillance checks, I need to review footage from yesterday between 3 PM and 5 PM. The camera "front_garden" should have the recording for that period. I need to retrieve this specific recorded feed. The start time for the recording was at 15:00 on April 22, 2023, and it ended at 17:00 on the same day.\n\nTo summarize, I request the execution of the following functions with the provided details:\n1. Retrieve the live feed from the "front_door" camera at 1080p quality.\n2. Start a 30-minute recording of the live feed from the "front_door" camera.\n3. Retrieve the recorded feed from the "front_garden" camera, focusing on the time period between 15:00 and 17:00 on April 22, 2023.\n\nThank you for assisting with the management of my home security camera feeds.'},
  {'from': 'gpt',
   'value': '<tool_call>\n{"name": "get_camera_live_feed", "arguments": {"camera_id": "front_door", "stream_quality": "1080p"}}\n</tool_call>\n<tool_call>\n{"name": "record_camera_feed", "arguments": {"camera_id": "front_door", "duration": 30}}\n</tool_call>\n<tool_call>\n{"name": "get_recorded_feed", "arguments": {"camera_id": "front_garden", "start_time": "2023-04-22T15:00:00Z", "end_time": "2023-04-22T17:00:00Z"}}\n</tool_call>\n'},
  {'from': 'tool',
   'value': '<tool_response>\n{"name": "get_camera_live_feed", "content": {"camera_id": "front_door", "stream_quality": "1080p", "live_feed_url": "https://homecam.example.com/live/front_door_1080p"}}\n</tool_response>\n<tool_response>\n{"name": "record_camera_feed", "content": {"camera_id": "front_door", "duration": 30, "recording_status": "started", "recording_url": "https://homecam.example.com/recordings/front_door_20230423T143000Z.mp4"}}\n</tool_response>\n<tool_response>\n{"name": "get_recorded_feed", "content": {"camera_id": "front_garden", "start_time": "2023-04-22T15:00:00Z", "end_time": "2023-04-22T17:00:00Z", "recorded_feed_url": "https://homecam.example.com/recordings/front_garden_20230422T150000Z_to_20230422T170000Z.mp4"}}\n</tool_response>\n'},
  {'from': 'gpt',
   'value': 'I have successfully executed all the requested functions for your home security cameras. Here are the results:\n\n1. **Live Feed from "front_door" Camera:**\n   - You can view the high-definition 1080p live feed from your front door camera at the [following link](https://homecam.example.com/live/front_door_1080p).\n\n2. **Recording of "front_door" Camera:**\n   - The 30-minute recording of the live feed from the "front_door" camera has been started successfully. You will be able to access the recorded feed at [this link](https://homecam.example.com/recordings/front_door_20230423T143000Z.mp4) once the recording completes.\n\n3. **Retrieved Recorded Feed from "front_garden" Camera:**\n   - The requested recorded feed from the "front_garden" camera for the period between 3 PM and 5 PM on April 22, 2023, is available at the [following link](https://homecam.example.com/recordings/front_garden_20230422T150000Z_to_20230422T170000Z.mp4).\n\nPlease use the provided links to manage and review your home security camera feeds. If you require further assistance or have any more tasks related to your security system, feel free to let me know.'}],
 'tools': '[{"type": "function", "function": {"name": "get_camera_live_feed", "description": "Retrieves the live feed from a specified security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the camera."}, "stream_quality": {"type": "string", "description": "The desired quality of the live stream.", "enum": ["720p", "1080p", "4k"]}}, "required": ["camera_id"]}}}, {"type": "function", "function": {"name": "list_all_cameras", "description": "Lists all the security cameras connected to the home network.", "parameters": {"type": "object", "properties": {"include_offline": {"type": "boolean", "description": "Whether to include cameras that are currently offline.", "default": false}}, "required": []}}}, {"type": "function", "function": {"name": "record_camera_feed", "description": "Starts recording the live feed from a specified security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the camera."}, "duration": {"type": "integer", "description": "The duration in minutes for which to record the feed.", "default": 60}}, "required": ["camera_id"]}}}, {"type": "function", "function": {"name": "get_recorded_feed", "description": "Retrieves a previously recorded feed from a specified security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the camera."}, "start_time": {"type": "string", "description": "The start time of the recording to retrieve, in ISO 8601 format."}, "end_time": {"type": "string", "description": "The end time of the recording to retrieve, in ISO 8601 format."}}, "required": ["camera_id", "start_time", "end_time"]}}}, {"type": "function", "function": {"name": "pan_tilt_camera", "description": "Controls the pan and tilt functions of a PTZ (Pan-Tilt-Zoom) security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the PTZ camera."}, "pan_angle": {"type": "integer", "description": "The angle in degrees to pan the camera. Positive values pan right, negative values pan left."}, "tilt_angle": {"type": "integer", "description": "The angle in degrees to tilt the camera. Positive values tilt up, negative values tilt down."}}, "required": ["camera_id", "pan_angle", "tilt_angle"]}}}]',
 'category': 'IoT and Home Automation',
 'subcategory': 'Security Camera Management',
 'task': 'View and Manage Security Camera Feeds',
 'messages': [{'role': 'system',
   'content': 'You are a function calling AI model. You are provided with function signatures within <tools> </tools> XML tags. You may call one or more functions to assist with the user query. Don\'t make assumptions about what values to plug into functions.\n<tools>\n[{"type": "function", "function": {"name": "get_camera_live_feed", "description": "Retrieves the live feed from a specified security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the camera."}, "stream_quality": {"type": "string", "description": "The desired quality of the live stream.", "enum": ["720p", "1080p", "4k"]}}, "required": ["camera_id"]}}}, {"type": "function", "function": {"name": "list_all_cameras", "description": "Lists all the security cameras connected to the home network.", "parameters": {"type": "object", "properties": {"include_offline": {"type": "boolean", "description": "Whether to include cameras that are currently offline.", "default": false}}, "required": []}}}, {"type": "function", "function": {"name": "record_camera_feed", "description": "Starts recording the live feed from a specified security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the camera."}, "duration": {"type": "integer", "description": "The duration in minutes for which to record the feed.", "default": 60}}, "required": ["camera_id"]}}}, {"type": "function", "function": {"name": "get_recorded_feed", "description": "Retrieves a previously recorded feed from a specified security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the camera."}, "start_time": {"type": "string", "description": "The start time of the recording to retrieve, in ISO 8601 format."}, "end_time": {"type": "string", "description": "The end time of the recording to retrieve, in ISO 8601 format."}}, "required": ["camera_id", "start_time", "end_time"]}}}, {"type": "function", "function": {"name": "pan_tilt_camera", "description": "Controls the pan and tilt functions of a PTZ (Pan-Tilt-Zoom) security camera.", "parameters": {"type": "object", "properties": {"camera_id": {"type": "string", "description": "The unique identifier for the PTZ camera."}, "pan_angle": {"type": "integer", "description": "The angle in degrees to pan the camera. Positive values pan right, negative values pan left."}, "tilt_angle": {"type": "integer", "description": "The angle in degrees to tilt the camera. Positive values tilt up, negative values tilt down."}}, "required": ["camera_id", "pan_angle", "tilt_angle"]}}}]\n</tools>\nFor each function call return a json object with function name and arguments within <tool_call> </tool_call> tags with the following schema:\n<tool_call>\n{"name": <function-name>, "arguments": <args-dict>}\n</tool_call>\n'},
  {'role': 'user',
   'content': 'I\'ve recently installed a new security system at my home, and I want to ensure everything is functioning as it should. Specifically, I\'d like to start by checking the live feed from the camera located at the front door to monitor any activity. The camera has a unique identifier, which I\'ve already configured to be "front_door." I\'d prefer to view the live stream in high definition, so a 1080p quality would be ideal. Could you please call the appropriate function to retrieve the live feed from my front door camera in 1080p quality and provide me with the link to the stream?\n\nFollowing this, I would also like to record the live feed from this camera for the next 30 minutes. This is to test the recording feature and to keep an archived copy for security purposes. Please initiate the recording function for the "front_door" camera with a recording duration of 30 minutes.\n\nLastly, as part of my routine surveillance checks, I need to review footage from yesterday between 3 PM and 5 PM. The camera "front_garden" should have the recording for that period. I need to retrieve this specific recorded feed. The start time for the recording was at 15:00 on April 22, 2023, and it ended at 17:00 on the same day.\n\nTo summarize, I request the execution of the following functions with the provided details:\n1. Retrieve the live feed from the "front_door" camera at 1080p quality.\n2. Start a 30-minute recording of the live feed from the "front_door" camera.\n3. Retrieve the recorded feed from the "front_garden" camera, focusing on the time period between 15:00 and 17:00 on April 22, 2023.\n\nThank you for assisting with the management of my home security camera feeds.'},
  {'role': 'assistant',
   'content': '<tool_call>\n{"name": "get_camera_live_feed", "arguments": {"camera_id": "front_door", "stream_quality": "1080p"}}\n</tool_call>\n<tool_call>\n{"name": "record_camera_feed", "arguments": {"camera_id": "front_door", "duration": 30}}\n</tool_call>\n<tool_call>\n{"name": "get_recorded_feed", "arguments": {"camera_id": "front_garden", "start_time": "2023-04-22T15:00:00Z", "end_time": "2023-04-22T17:00:00Z"}}\n</tool_call>\n'},
  {'role': 'tool',
   'content': '<tool_response>\n{"name": "get_camera_live_feed", "content": {"camera_id": "front_door", "stream_quality": "1080p", "live_feed_url": "https://homecam.example.com/live/front_door_1080p"}}\n</tool_response>\n<tool_response>\n{"name": "record_camera_feed", "content": {"camera_id": "front_door", "duration": 30, "recording_status": "started", "recording_url": "https://homecam.example.com/recordings/front_door_20230423T143000Z.mp4"}}\n</tool_response>\n<tool_response>\n{"name": "get_recorded_feed", "content": {"camera_id": "front_garden", "start_time": "2023-04-22T15:00:00Z", "end_time": "2023-04-22T17:00:00Z", "recorded_feed_url": "https://homecam.example.com/recordings/front_garden_20230422T150000Z_to_20230422T170000Z.mp4"}}\n</tool_response>\n'},
  {'role': 'assistant',
   'content': 'I have successfully executed all the requested functions for your home security cameras. Here are the results:\n\n1. **Live Feed from "front_door" Camera:**\n   - You can view the high-definition 1080p live feed from your front door camera at the [following link](https://homecam.example.com/live/front_door_1080p).\n\n2. **Recording of "front_door" Camera:**\n   - The 30-minute recording of the live feed from the "front_door" camera has been started successfully. You will be able to access the recorded feed at [this link](https://homecam.example.com/recordings/front_door_20230423T143000Z.mp4) once the recording completes.\n\n3. **Retrieved Recorded Feed from "front_garden" Camera:**\n   - The requested recorded feed from the "front_garden" camera for the period between 3 PM and 5 PM on April 22, 2023, is available at the [following link](https://homecam.example.com/recordings/front_garden_20230422T150000Z_to_20230422T170000Z.mp4).\n\nPlease use the provided links to manage and review your home security camera feeds. If you require further assistance or have any more tasks related to your security system, feel free to let me know.'}]}

In [111]:
# check if all system prompt start with "You are a function calling AI model"
for example in hermes_data:
    if example['messages'][0]['role'] == 'system' and not example['messages'][0]['content'].startswith('You are a function calling AI model'):
        print(example['messages'][0]['content'])

You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema.
<tools>
[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of open-ended questions related to the document, that are potentially ambiguous.", "parameters": {"type": "object", "properties": {"open_ended_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["open_ended_questions"]}}}]
</tools>
For each extraction function call return a json object with function name and arguments followed by a <tool_call> tag with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>
You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema.
<tools>
[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of questions that ask for clarification on an ambiguous or unclear statement in the document. These help resolve confusion.", "parameters": {"type": "object", "properties": {"clarification_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["clarification_questions"]}}}]
</tools>
For each extraction function call return a json object with function name and arguments followed by a <tool_call> tag with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>
You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema.
<tools>
[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of questions that ask for advice or suggestions on how to approach a specific scenario found in the document.", "parameters": {"type": "object", "properties": {"advice_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["advice_questions"]}}}]
</tools>
For each extraction function call return a json object with function name and arguments followed by a <tool_call> tag with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>
You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema.
<tools>
[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of questions that ask what is likely to happen next based on the information in the document. These assess ability to extrapolate.", "parameters": {"type": "object", "properties": {"prediction_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["prediction_questions"]}}}]
</tools>
For each extraction function call return a json object with function name and arguments followed by a <tool_call> tag with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>
You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema.
<tools>
[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of open-ended questions related to the document, that are potentially ambiguous.", "parameters": {"type": "object", "properties": {"open_ended_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["open_ended_questions"]}}}]
</tools>
For each extraction function call return a json object with function name and arguments followed by a <tool_call> tag with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>
You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema.
<tools>
[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of questions that focus on summarizing a specific topic found in the document.", "parameters": {"type": "object", "properties": {"topic_summarization_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["topic_summarization_questions"]}}}]
</tools>
For each extraction function call return a json object with function name and arguments followed by a <tool_call> tag with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>
You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema.
<tools>
[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of questions that ask how to diagnose or solve a problem outlined in the document. These assesses ability to troubleshoot.", "parameters": {"type": "object", "properties": {"troubleshooting_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["troubleshooting_questions"]}}}]
</tools>
For each extraction function call return a json object with function name and arguments followed by a <tool_call> tag with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>
You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema.
<tools>
[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of questions that require making logical inferences based on the information in the document. These test understanding.", "parameters": {"type": "object", "properties": {"inference_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["inference_questions"]}}}]
</tools>
For each extraction function call return a json object with function name and arguments followed by a <tool_call> tag with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>
You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema.
<tools>
[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of questions that focus on summarizing a specific topic found in the document.", "parameters": {"type": "object", "properties": {"topic_summarization_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["topic_summarization_questions"]}}}]
</tools>
For each extraction function call return a json object with function name and arguments followed by a <tool_call> tag with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>
You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema. {"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of questions that ask how ideas in the document
are connected or relate to each other. These identify relationships between concepts.", "parameters":
<tools>
[{"type": "object", "properties": {"connection_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["connection_questions"]}}}]
</tools>
For each extraction function call return a json object with function name and arguments followed by a <tool_call> tag with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>
You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema.
<tools>
[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of questions that ask for reasoning behind a design decision, product specification, or method described in the document. These reveals thought processes.", "parameters": {"type": "object", "properties": {"justification_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["justification_questions"]}}}]
</tools>
For each extraction function call return a json object with function name and arguments followed by a <tool_call> tag with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>
You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema.
<tools>
[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of questions that ask what is likely to happen next based on the information in the document. These assess ability to extrapolate.", "parameters": {"type": "object", "properties": {"prediction_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["prediction_questions"]}}}]
</tools>
For each extraction function call return a json object with function name and arguments followed by a <tool_call> tag with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>
You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema.
<tools>
[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of questions that require making logical inferences based on the information in the document. These test understanding.", "parameters": {"type": "object", "properties": {"inference_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["inference_questions"]}}}]
</tools>
For each extraction function call return a json object with function name and arguments followed by a <tool_call> tag with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>
You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema.
<tools>
[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of direct questions related to the document that have a single, unambiguous answer.", "parameters": {"type": "object", "properties": {"directed_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["directed_questions"]}}}]
</tools>
For each extraction function call return a json object with function name and arguments followed by a <tool_call> tag with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>
You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema.
<tools>
[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of questions that ask how a concept or information from the document can be applied to a real-world situation. These assess ability to apply knowledge.", "parameters": {"type": "object", "properties": {"application_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["application_questions"]}}}]
</tools>
For each extraction function call return a json object with function name and arguments followed by a <tool_call> tag with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>
You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema.
<tools>
[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of questions that ask for an assessment or critique of an idea, argument, or proposal in the document. These test critical thinking.", "parameters": {"type": "object", "properties": {"evaluation_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["evaluation_questions"]}}}]
</tools>
For each extraction function call return a json object with function name and arguments followed by a <tool_call> tag with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>
You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema.
<tools>
[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of questions that focus on summarizing a specific topic found in the document.", "parameters": {"type": "object", "properties": {"topic_summarization_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["topic_summarization_questions"]}}}]
</tools>
For each extraction function call return a json object with function name and arguments followed by a <tool_call> tag with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>
You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema.
<tools>
[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of questions that ask what is likely to happen next based on the information in the document. These assess ability to extrapolate.", "parameters": {"type": "object", "properties": {"prediction_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["prediction_questions"]}}}]
</tools>
For each extraction function call return a json object with function name and arguments followed by a <tool_call> tag with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>
You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema.
<tools>
[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of questions that ask how to diagnose or solve a problem outlined in the document. These assesses ability to troubleshoot.", "parameters": {"type": "object", "properties": {"troubleshooting_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["troubleshooting_questions"]}}}]
</tools>
For each extraction function call return a json object with function name and arguments followed by a <tool_call> tag with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>
You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema.
<tools>
[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of questions that ask what is likely to happen next based on the information in the document. These assess ability to extrapolate.", "parameters": {"type": "object", "properties": {"prediction_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["prediction_questions"]}}}]
</tools>
For each extraction function call return a json object with function name and arguments followed by a <tool_call> tag with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>
You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema.
<tools>
[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of questions that require making logical inferences based on the information in the document. These test understanding.", "parameters": {"type": "object", "properties": {"inference_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["inference_questions"]}}}]
</tools>
For each extraction function call return a json object with function name and arguments followed by a <tool_call> tag with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>

In [112]:
# check if all system prompt end with 
# <tool_call>
# {"name": <function-name>, "arguments": <args-dict>}
# </tool_call>

s = """
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>
""".strip()

for example in hermes_data:
    if example['messages'][0]['role'] == 'system' and not example['messages'][0]['content'].strip().endswith(s):
        print(example['messages'][0]['content'])

In [113]:
# Unique ways to telling the model to output a tool call
unique_tool_call_prompts = set()
for example in hermes_data:
    if example['messages'][0]['role'] == 'system':
        prompt = example['messages'][0]['content'].strip().splitlines()[-4]
        unique_tool_call_prompts.add(prompt)

len(unique_tool_call_prompts)

2

In [114]:
# unique system prompts
unique_system_prompts = set()
for example in hermes_data:
    if example['messages'][0]['role'] == 'system':
        unique_system_prompts.add(example['messages'][0]['content'].strip())

len(unique_system_prompts)

1113

In [115]:
len(hermes_data)

1893

In [116]:
for x in unique_system_prompts:
    print(x)
    break

You are a function calling AI model. You are provided with function signatures within <tools> </tools> XML tags. You may call one or more functions to assist with the user query. Don't make assumptions about what values to plug into functions.
<tools>
[{"type": "function", "function": {"name": "manage_artist_lineup", "description": "Manages the lineup of artists for an event, including stage assignments and performance times.", "parameters": {"type": "object", "properties": {"festival_id": {"type": "string", "description": "The unique identifier of the festival."}, "artists": {"type": "array", "description": "A list of artists with their performance details.", "items": {"type": "object", "properties": {"artist_id": {"type": "string", "description": "The unique identifier of the artist."}, "stage": {"type": "string", "description": "The stage where the artist will perform."}, "performance_time": {"type": "string", "description": "The scheduled start time of the artist's performance in ISO 8601 format."}}, "required": ["artist_id", "stage", "performance_time"]}}}, "required": ["festival_id", "artists"]}}}, {"type": "function", "function": {"name": "track_ticket_sales", "description": "Tracks ticket sales for an event on a specific date.", "parameters": {"type": "object", "properties": {"festival_id": {"type": "string", "description": "The unique identifier of the festival."}, "date": {"type": "string", "description": "The date for which to track ticket sales in ISO 8601 format."}}, "required": ["festival_id", "date"]}}}, {"type": "function", "function": {"name": "coordinate_event_logistics", "description": "Coordinates the logistics for an event, including security, medical staff, and parking.", "parameters": {"type": "object", "properties": {"festival_id": {"type": "string", "description": "The unique identifier of the festival."}, "logistics_details": {"type": "object", "properties": {"security_staff": {"type": "integer", "description": "The number of security staff members required."}, "medical_staff": {"type": "integer", "description": "The number of medical staff members required."}, "parking_spots": {"type": "integer", "description": "The number of parking spots available."}}, "required": ["security_staff", "medical_staff", "parking_spots"]}}, "required": ["festival_id", "logistics_details"]}}}]
</tools>
For each function call return a json object with function name and arguments within <tool_call> </tool_call> tags with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>

In [117]:
print(next(iter(unique_system_prompts)))

You are a function calling AI model. You are provided with function signatures within <tools> </tools> XML tags. You may call one or more functions to assist with the user query. Don't make assumptions about what values to plug into functions.
<tools>
[{"type": "function", "function": {"name": "manage_artist_lineup", "description": "Manages the lineup of artists for an event, including stage assignments and performance times.", "parameters": {"type": "object", "properties": {"festival_id": {"type": "string", "description": "The unique identifier of the festival."}, "artists": {"type": "array", "description": "A list of artists with their performance details.", "items": {"type": "object", "properties": {"artist_id": {"type": "string", "description": "The unique identifier of the artist."}, "stage": {"type": "string", "description": "The stage where the artist will perform."}, "performance_time": {"type": "string", "description": "The scheduled start time of the artist's performance in ISO 8601 format."}}, "required": ["artist_id", "stage", "performance_time"]}}}, "required": ["festival_id", "artists"]}}}, {"type": "function", "function": {"name": "track_ticket_sales", "description": "Tracks ticket sales for an event on a specific date.", "parameters": {"type": "object", "properties": {"festival_id": {"type": "string", "description": "The unique identifier of the festival."}, "date": {"type": "string", "description": "The date for which to track ticket sales in ISO 8601 format."}}, "required": ["festival_id", "date"]}}}, {"type": "function", "function": {"name": "coordinate_event_logistics", "description": "Coordinates the logistics for an event, including security, medical staff, and parking.", "parameters": {"type": "object", "properties": {"festival_id": {"type": "string", "description": "The unique identifier of the festival."}, "logistics_details": {"type": "object", "properties": {"security_staff": {"type": "integer", "description": "The number of security staff members required."}, "medical_staff": {"type": "integer", "description": "The number of medical staff members required."}, "parking_spots": {"type": "integer", "description": "The number of parking spots available."}}, "required": ["security_staff", "medical_staff", "parking_spots"]}}, "required": ["festival_id", "logistics_details"]}}}]
</tools>
For each function call return a json object with function name and arguments within <tool_call> </tool_call> tags with the following schema:
<tool_call>
{"name": <function-name>, "arguments": <args-dict>}
</tool_call>

In [118]:
# drop tools
# drop tool call prompt

import re
ptrn = re.compile(r"<tools>\n.*\n<\/tools>", flags=re.DOTALL)

# This is a formatting error in the system prompt for hermes. we will drop these examples 
bad_s = """You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema. {"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of questions that ask how ideas in the document 
are connected or relate to each other. These identify relationships between concepts.", "parameters":"""


cleaned_examples = []
for example in hermes_data:
    system_prompt = example['messages'][0]['content']
    original_system_prompt = system_prompt

    # drop tool call prompt
    system_prompt = system_prompt.strip().splitlines()[:-4]
    system_prompt = "\n".join(system_prompt)

    # drop tool calls
    just_before_dropping_tool_calls = system_prompt
    system_prompt = ptrn.sub("", system_prompt).strip()
    if system_prompt.strip() == bad_s: continue

    example['messages'][0]['content'] = system_prompt
    cleaned_examples.append(example)
    
len(hermes_data), len(cleaned_examples)

(1893, 1832)

In [119]:
example['messages'][0]['content']

"You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema."

In [73]:
ptrn

re.compile(r'<tools>\n.*\n<\/tools>', re.DOTALL|re.UNICODE)

In [120]:
# convert tool def into openai compatible tool def

tool_call_ptrn = re.compile(r"<tools>\n(.*)\n<\/tools>", flags=re.DOTALL)
for example in cleaned_examples:
    original_system_prompt = example['conversations'][0]['value']

    matches = re.search(tool_call_ptrn, original_system_prompt)
    if matches is None or len(matches.groups()) < 1: raise ValueError('matches is None')
    group = matches.groups()[0]
    group = group.strip()

    if not group: raise ValueError('group is empty')
    if '\n' in group: raise ValueError('group contains newlines. didn\'t expect that.')

    # tools are openai compatible tool defs
    tools = json.loads(group)
    example['tools'] = tools

In [121]:
tools

[{'type': 'function',
  'function': {'name': 'ExpertQAExtractor',
   'description': 'Extracts a list of questions that focus on summarizing a specific topic found in the document.',
   'parameters': {'type': 'object',
    'properties': {'topic_summarization_questions': {'type': 'array',
      'items': {'type': 'string'}}},
    'required': ['topic_summarization_questions']}}}]

In [86]:
example['messages'][1]['content']

'I\'ve recently installed a new security system at my home, and I want to ensure everything is functioning as it should. Specifically, I\'d like to start by checking the live feed from the camera located at the front door to monitor any activity. The camera has a unique identifier, which I\'ve already configured to be "front_door." I\'d prefer to view the live stream in high definition, so a 1080p quality would be ideal. Could you please call the appropriate function to retrieve the live feed from my front door camera in 1080p quality and provide me with the link to the stream?\n\nFollowing this, I would also like to record the live feed from this camera for the next 30 minutes. This is to test the recording feature and to keep an archived copy for security purposes. Please initiate the recording function for the "front_door" camera with a recording duration of 30 minutes.\n\nLastly, as part of my routine surveillance checks, I need to review footage from yesterday between 3 PM and 5 PM. The camera "front_garden" should have the recording for that period. I need to retrieve this specific recorded feed. The start time for the recording was at 15:00 on April 22, 2023, and it ended at 17:00 on the same day.\n\nTo summarize, I request the execution of the following functions with the provided details:\n1. Retrieve the live feed from the "front_door" camera at 1080p quality.\n2. Start a 30-minute recording of the live feed from the "front_door" camera.\n3. Retrieve the recorded feed from the "front_garden" camera, focusing on the time period between 15:00 and 17:00 on April 22, 2023.\n\nThank you for assisting with the management of my home security camera feeds.'

In [91]:
from dotenv import load_dotenv; load_dotenv()
from openai import OpenAI
import os

client = OpenAI(base_url='https://api.together.xyz/v1', api_key=os.environ['TOGETHER_API_KEY'])
response = client.chat.completions.create(
    model='zai-org/GLM-4.5-Air-FP8',
    messages=[
        {"role": "user", "content": example['messages'][1]['content']}
    ],
    tools=tools,
    tool_choice='auto',
)
print(response.choices[0].message)

ChatCompletionMessage(content="I'll help you manage your home security camera feeds by executing all three requested functions. Let me process each request step by step.", refusal=None, role='assistant', annotations=None, audio=None, function_call=None, tool_calls=[ChatCompletionMessageFunctionToolCall(id='call_869b3bc5525b48eea862b4f8', function=Function(arguments='{"camera_id": "front_door", "stream_quality": "1080p"}', name='get_camera_live_feed'), type='function', index=-1), ChatCompletionMessageFunctionToolCall(id='call_14f01b80a2bc40b3b52c7e15', function=Function(arguments='{"camera_id": "front_door", "duration": 30}', name='record_camera_feed'), type='function', index=-1), ChatCompletionMessageFunctionToolCall(id='call_6a140c4f06e74afc82ba197e', function=Function(arguments='{"camera_id": "front_garden", "start_time": "2023-04-22T15:00:00", "end_time": "2023-04-22T17:00:00"}', name='get_recorded_feed'), type='function', index=-1)], reasoning='The user is asking me to perform three distinct tasks:\n\n1. Retrieve the live feed from the "front_door" camera at 1080p quality\n2. Start a 30-minute recording from the "front_door" camera  \n3. Retrieve recorded feed from the "front_garden" camera between 15:00 and 17:00 on April 22, 2023\n\nLet me analyze each request:\n\n1. For the live feed:\n   - camera_id: "front_door" (provided)\n   - stream_quality: "1080p" (provided, and it\'s one of the allowed values)\n   - This requires the get_camera_live_feed function\n\n2. For the recording:\n   - camera_id: "front_door" (provided)\n   - duration: 30 minutes (provided)\n   - This requires the record_camera_feed function\n\n3. For the recorded feed retrieval:\n   - camera_id: "front_garden" (provided)\n   - start_time: "15:00 on April 22, 2023" - this needs to be converted to ISO 8601 format: "2023-04-22T15:00:00"\n   - end_time: "17:00 on April 22, 2023" - this needs to be converted to ISO 8601 format: "2023-04-22T17:00:00"\n   - This requires the get_recorded_feed function\n\nAll required parameters are provided, so I can proceed with all three function calls.')

In [93]:
response.choices[0].message.tool_calls

[ChatCompletionMessageFunctionToolCall(id='call_869b3bc5525b48eea862b4f8', function=Function(arguments='{"camera_id": "front_door", "stream_quality": "1080p"}', name='get_camera_live_feed'), type='function', index=-1),
 ChatCompletionMessageFunctionToolCall(id='call_14f01b80a2bc40b3b52c7e15', function=Function(arguments='{"camera_id": "front_door", "duration": 30}', name='record_camera_feed'), type='function', index=-1),
 ChatCompletionMessageFunctionToolCall(id='call_6a140c4f06e74afc82ba197e', function=Function(arguments='{"camera_id": "front_garden", "start_time": "2023-04-22T15:00:00", "end_time": "2023-04-22T17:00:00"}', name='get_recorded_feed'), type='function', index=-1)]

In [94]:
example = hermes_data[0]
for x in example['messages']:
    if x['role'] == 'assistant':
        print(x['content'])
        break

<tool_call>
{"name": "get_camera_live_feed", "arguments": {"camera_id": "front_door", "stream_quality": "1080p"}}
</tool_call>
<tool_call>
{"name": "record_camera_feed", "arguments": {"camera_id": "front_door", "duration": 30}}
</tool_call>
<tool_call>
{"name": "get_recorded_feed", "arguments": {"camera_id": "front_garden", "start_time": "2023-04-22T15:00:00Z", "end_time": "2023-04-22T17:00:00Z"}}
</tool_call>

In [127]:
from copy import deepcopy

separated_examples = []
for example in cleaned_examples:
    # count 'assistant' messages
    for i, x in enumerate(example['messages']):
        if x['role'] == 'assistant':
            _tmp = deepcopy(example)
            _tmp['messages'] = _tmp['messages'][:i+1]
            separated_examples.append(_tmp)

len(cleaned_examples), len(separated_examples)

(1832, 2759)

# Corrupt the messages

In [128]:
# convert to hf dataset obj
import pandas as pd

df = pd.DataFrame(separated_examples)
df.head()

,source_dataset,source_config,source_row_idx,id,conversations,tools,category,subcategory,task,messages
0,NousResearch/hermes-function-calling-v1,func_calling,0,82088305-310b-45cb-ac76-ab273503b5cd,"[{'from': 'system', 'value': 'You are a functi...","[{'type': 'function', 'function': {'name': 'ge...",IoT and Home Automation,Security Camera Management,View and Manage Security Camera Feeds,"[{'role': 'system', 'content': 'You are a func..."
1,NousResearch/hermes-function-calling-v1,func_calling,0,82088305-310b-45cb-ac76-ab273503b5cd,"[{'from': 'system', 'value': 'You are a functi...","[{'type': 'function', 'function': {'name': 'ge...",IoT and Home Automation,Security Camera Management,View and Manage Security Camera Feeds,"[{'role': 'system', 'content': 'You are a func..."
2,NousResearch/hermes-function-calling-v1,func_calling,1,bd48c5c1-186a-4120-be4a-61974d22fc8b,"[{'from': 'system', 'value': 'You are a functi...","[{'type': 'function', 'function': {'name': 'in...",IoT and Home Automation,Smart Home Setup,Set Up a Smart Home System,"[{'role': 'system', 'content': 'You are a func..."
3,NousResearch/hermes-function-calling-v1,func_calling,1,bd48c5c1-186a-4120-be4a-61974d22fc8b,"[{'from': 'system', 'value': 'You are a functi...","[{'type': 'function', 'function': {'name': 'in...",IoT and Home Automation,Smart Home Setup,Set Up a Smart Home System,"[{'role': 'system', 'content': 'You are a func..."
4,NousResearch/hermes-function-calling-v1,func_calling,2,b099e2c1-8459-4848-bd4f-0385e0d45d59,"[{'from': 'system', 'value': 'You are a functi...","[{'type': 'function', 'function': {'name': 'se...",IoT and Home Automation,Thermostat Control,Adjust Smart Thermostat Settings,"[{'role': 'system', 'content': 'You are a func..."

In [129]:
# duplicate rows N times 
print(df.shape)
df = pd.concat([df] * 10, ignore_index=True)
print(df.shape)
df.head()

(2759, 10)
(27590, 10)

,source_dataset,source_config,source_row_idx,id,conversations,tools,category,subcategory,task,messages
0,NousResearch/hermes-function-calling-v1,func_calling,0,82088305-310b-45cb-ac76-ab273503b5cd,"[{'from': 'system', 'value': 'You are a functi...","[{'type': 'function', 'function': {'name': 'ge...",IoT and Home Automation,Security Camera Management,View and Manage Security Camera Feeds,"[{'role': 'system', 'content': 'You are a func..."
1,NousResearch/hermes-function-calling-v1,func_calling,0,82088305-310b-45cb-ac76-ab273503b5cd,"[{'from': 'system', 'value': 'You are a functi...","[{'type': 'function', 'function': {'name': 'ge...",IoT and Home Automation,Security Camera Management,View and Manage Security Camera Feeds,"[{'role': 'system', 'content': 'You are a func..."
2,NousResearch/hermes-function-calling-v1,func_calling,1,bd48c5c1-186a-4120-be4a-61974d22fc8b,"[{'from': 'system', 'value': 'You are a functi...","[{'type': 'function', 'function': {'name': 'in...",IoT and Home Automation,Smart Home Setup,Set Up a Smart Home System,"[{'role': 'system', 'content': 'You are a func..."
3,NousResearch/hermes-function-calling-v1,func_calling,1,bd48c5c1-186a-4120-be4a-61974d22fc8b,"[{'from': 'system', 'value': 'You are a functi...","[{'type': 'function', 'function': {'name': 'in...",IoT and Home Automation,Smart Home Setup,Set Up a Smart Home System,"[{'role': 'system', 'content': 'You are a func..."
4,NousResearch/hermes-function-calling-v1,func_calling,2,b099e2c1-8459-4848-bd4f-0385e0d45d59,"[{'from': 'system', 'value': 'You are a functi...","[{'type': 'function', 'function': {'name': 'se...",IoT and Home Automation,Thermostat Control,Adjust Smart Thermostat Settings,"[{'role': 'system', 'content': 'You are a func..."

In [130]:
# add a new column to the dataset that will be used to determine the type of corruption

import numpy as np

AVAILABLE_CORRUPTION_TYPES = ['no_corruption', 'delete_content', 'corrupt_content', 'add_unnecessary_content', 'delete_tool_call', 'corrupt_tool_call_name', 'corrupt_tool_call_argument', 'add_extra_tool_call']
# for now give equal probability to each corruption type
df['corruption_type'] = np.random.choice(AVAILABLE_CORRUPTION_TYPES, size=df.shape[0])
df.head()

,source_dataset,source_config,source_row_idx,id,conversations,tools,category,subcategory,task,messages,corruption_type
0,NousResearch/hermes-function-calling-v1,func_calling,0,82088305-310b-45cb-ac76-ab273503b5cd,"[{'from': 'system', 'value': 'You are a functi...","[{'type': 'function', 'function': {'name': 'ge...",IoT and Home Automation,Security Camera Management,View and Manage Security Camera Feeds,"[{'role': 'system', 'content': 'You are a func...",delete_content
1,NousResearch/hermes-function-calling-v1,func_calling,0,82088305-310b-45cb-ac76-ab273503b5cd,"[{'from': 'system', 'value': 'You are a functi...","[{'type': 'function', 'function': {'name': 'ge...",IoT and Home Automation,Security Camera Management,View and Manage Security Camera Feeds,"[{'role': 'system', 'content': 'You are a func...",delete_tool_call
2,NousResearch/hermes-function-calling-v1,func_calling,1,bd48c5c1-186a-4120-be4a-61974d22fc8b,"[{'from': 'system', 'value': 'You are a functi...","[{'type': 'function', 'function': {'name': 'in...",IoT and Home Automation,Smart Home Setup,Set Up a Smart Home System,"[{'role': 'system', 'content': 'You are a func...",corrupt_tool_call_name
3,NousResearch/hermes-function-calling-v1,func_calling,1,bd48c5c1-186a-4120-be4a-61974d22fc8b,"[{'from': 'system', 'value': 'You are a functi...","[{'type': 'function', 'function': {'name': 'in...",IoT and Home Automation,Smart Home Setup,Set Up a Smart Home System,"[{'role': 'system', 'content': 'You are a func...",delete_tool_call
4,NousResearch/hermes-function-calling-v1,func_calling,2,b099e2c1-8459-4848-bd4f-0385e0d45d59,"[{'from': 'system', 'value': 'You are a functi...","[{'type': 'function', 'function': {'name': 'se...",IoT and Home Automation,Thermostat Control,Adjust Smart Thermostat Settings,"[{'role': 'system', 'content': 'You are a func...",corrupt_content

In [148]:
# use llms for corrupting the messages
# corruption types for llms: corrupt_content, add_unnecessary_content, corrupt_tool_call_name, corrupt_tool_call_argument, add_extra_tool_call

CORRUPTION_PROMPT_BASE = """
You are generating a deliberately corrupted assistant draft for adapter-training.
You will receive:
- the original system prompt with tool definitions if any
- the original conversation between the user and the assistant
- the gold assistant response
""".strip()

CORRUPTION_SYSTEM_PROMPTS = {
    "corrupt_content": "Corrupt the content of the assistant response.",
    "add_unnecessary_content": "Produce a draft with extra assistant text that should not be there.",
    "corrupt_tool_call_name": "Rewrite the given tool call with a wrong tool name.",
    "corrupt_tool_call_argument": "Rewrite the given tool call with wrong argument names or values or value types.",
    "add_extra_tool_call": "Produce an extra unnecessary tool call.",
}


CORRUPTION_PROMPT_RESPONSE_FORMAT = """
<corruption_output>
    <notes>[...]</notes>
    <content>if corrupted content</content>
    <tool_calls>if corrupted tool call</tool_calls>
</corruption_output>
"""

In [136]:
example

{'source_dataset': 'NousResearch/hermes-function-calling-v1',
 'source_config': 'func_calling',
 'source_row_idx': 1892,
 'id': '98c8fda0-ca02-4d3c-ac96-c5bd6bf6904a',
 'conversations': [{'from': 'system',
   'value': 'You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don\'t make assumptions about what values to plug into json schema. \n<tools>\n[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of questions that focus on summarizing a specific topic found in the document.", "parameters": {"type": "object", "properties": {"topic_summarization_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["topic_summarization_questions"]}}}]\n</tools>\nFor each extraction function call return a json object with function name and arguments followed by a <tool_call> tag with the following schema:\n<tool_call>\n{"name": <function-name>, "arguments": <args-dict>}\n</tool_call>'},
  {'from': 'human',
   'value': 'Can you help me extract queries from the following passage <passage> = - 3 x + y - z = 0 \nC50+^ A three-digit number has two properties. The tens-digit and the ones-digit add up to 5. If the number is written with the digits in the reverse order, and then subtracted \nSSS S L E B e e z e r : A F i r s t C o u r s e i n L i n e a r A l g e b r a 16 \nfrom the original number, the result is 792. Use a system of equations to find all of the three-digit numbers with these properties. \nC51+^ Find all of the six-digit numbers in which the first digit is one less than the second, the third digit is half the second, the fourth digit is three times the third and the last two digits form a number that equals the sum of the fourth and fifth. The sum of all the digits is 24. (From The MENSA Puzzle Calendar for January 9, 2006.) \nC52+^ Driving along, Terry notices that the last four digits on his car\'s odometer are palindromic. A mile later, the last five digits are palindromic. After driving another mile, the middle four digits are palindromic. One more mile, and all six are palindromic. What was the odometer reading when Terry first looked at it? Form a linear system of equations that expresses the requirements of this puzzle. (Car Talk Puzzler, National Public Radio, Week of January 21, 2008) (A car odometer displays six digits and a sequence is a palindrome if it reads the same left-to-right as right-to-left.) M10+^ Each sentence below has at least two meanings. Identify the source of the double meaning, and rewrite the sentence (at least twice) to clearly convey each meaning. \n1. They are baking potatoes. \n2. He bought many ripe pears and apricots. \n3. She likes his sculpture. \n4. I decided on the bus. \nM11+^ Discuss the difference in meaning of each of the following three almost identical sentences, which all have the same grammatical structure. (These are due to Keith Devlin.) \n1. She saw him in the park with a dog. \n2. She saw him in the park with a fountain. \n3. She saw him in the park with a telescope. \nM12+^ The following sentence, due to Noam Chomsky, has a correct grammatical structure, but is meaningless. Critique its faults. "Colorless green ideas sleep furiously." (Chomsky, Noam. Syntactic Structures, The Hague/Paris: Mouton, 1957. p. 15.) \nM13+^ Read the following sentence and form a mental picture of the situation. The baby cried and the mother picked it up. What assumptions did you make about the situation? \nM14 Discuss the difference in meaning of the following two almost identical sentences, which have nearly identical grammatical structure. (This antanaclasis is often attributed to the comedian Groucho Marx, but has earlier roots.) \n1. Time flies like an arrow. \n2. Fruit flies like a banana. \nM30+^ This problem appears in a middle-school mathematics textbook: Together Dan and Diane have $20. Together Diane and Donna have $15. How much do the three of them have in total? (Transition Mathematics, Second Edition, Scott Foresman Addison Wesley, \n1998. Problem 5-1.19.) \nM40 Solutions to the system in Example IS are given as \n (x 1 , x 2 , x 3 , x 4 ) = (- 1 - 2 a + 3b, 4 + a - 2 b, a, b) \nEvaluate the three equations of the original system with these expressions in a and b and verify that each equation is true, no matter what values are chosen for a and b. \nM70+^ We have seen in this section that systems of linear equations have limited possibilities for solution sets, and we will shortly prove Theorem PSSLS that describes these \nSSS S L E B e e z e r : A F i r s t C o u r s e i n L i n e a r A l g e b r a 17 \npossibilities exactly. This exercise will show that if we relax the requirement that our equations be linear, then the possibilities expand greatly. Consider a system of two equations in the two variables x and y, where the departure from linearity involves simply squaring the variables. \n x^2 - y^2 = 1 x^2 + y^2 = 4 \nAfter solving this system of nonlinear equations, replace the second equation in turn by x^2 + 2x + y^2 = 3, x^2 + y^2 = 1, x^2 - 4 x + y^2 = -3, -x^2 + y^2 = 1 and solve each resulting system of two equations in two variables. (This exercise includes suggestions from Don Kreher.) \nT10+^ Proof Technique D asks you to formulate a definition of what it means for a whole number to be odd. What is your definition? (Do not say "the opposite of even.") Is 6 odd? Is 11 odd? Justify your answers by using your definition. T20+^ Explain why the second equation operation in Definition EO requires that the scalar be nonzero, while in the third equation operation this restriction on the scalar is not present. \n### Section RREF \n### Reduced Row-Echelon Form \n After solving a few systems of equations, you will recognize that it does not matter so much what we call our variables, as opposed to what numbers act as their coefficients. A system in the variables x 1 , x 2 , x 3 would behave the same if we changed the names of the variables to a, b, c and kept all the constants the same and in the same places. In this section, we will isolate the key bits of information about a system of equations into something called a matrix, and then use this matrix to systematically solve the equations. Along the way we will obtain one of our most important and useful computational tools. \n##### Subsection MVNSE \n##### Matrix and Vector Notation for Systems of Equations \nDefinition M Matrix An m x n matrix is a rectangular layout of numbers from C having m rows and n columns. We will use upper-case Latin letters from the start of the alphabet (A, B, C,... ) to denote matrices and squared-off brackets to delimit the layout. Many use large parentheses instead of brackets -- the distinction is not important. Rows of a matrix will be referenced starting at the top and working down (i.e. row 1 is at the top) and columns will be referenced starting from the left (i.e. column 1 is at the left). For a matrix A, the notation [A]ij will refer to the complex number in row i and column j of A. \x03 Be careful with this notation for individual entries, since it is easy to think that [A]ij refers to the whole matrix. It does not. It is just a number, but is a convenient way to talk about the individual entries simultaneously. This notation will get a heavy workout once we get to Chapter M. Example AM A matrix \n B = \n [- 1 2 5 3 1 0 - 6 1 - 4 2 2 - 2 \n ] \n is a matrix with m = 3 rows and n = 4 columns. We can say that [B] 2 , 3 = -6 while [B] 3 , 4 = -2. 4 When we do equation operations on system of equations, the names of the variables really are not very important. Use x 1 , x 2 , x 3 , or a, b, c, or x, y, z, it really does not matter. In this subsection we will describe some notation that will make it easier to describe linear systems, solve the systems and describe the solution sets. Here is a list of definitions, laden with notation. Definition CV Column Vector A column vector of size m is an ordered list of m numbers, which is written in order vertically, starting at the top and proceeding to the bottom. At times, we will refer to a column vector as simply a vector. Column vectors will be written in bold, usually with lower case Latin letter from the end of the alphabet such as u, v, w, x, y, z. Some books like to write vectors with arrows, such as ~u. Writing by hand, some like to put arrows on top of the symbol, or a tilde underneath the symbol, as in u ~ \n. To refer to the entry or component of vector v in location i of the list, we write [v]i. \x03 Be careful with this notation. While the symbols [v]i might look somewhat substantial, as an object this represents just one entry of a vector, which is just a \nSSR R E F B e e z e r : A F i r s t C o u r s e i n L i n e a r A l g e b r a 19 \nsingle complex number. \nDefinition ZCV Zero Column Vector The zero vector of size m is the column vector of size m where each entry is the number zero, \n 0 = \n       0 0 0 .. . 0 \n       \nor defined much more compactly, [ 0 ]i = 0 for 1 <= i <= m. \x03 \nDefinition CM Coefficient Matrix For a system of linear equations, \n a 11 x 1 + a 12 x 2 + a 13 x 3 + * * * + a 1 nxn = b 1 a 21 x 1 + a 22 x 2 + a 23 x 3 + * * * + a 2 nxn = b 2 a 31 x 1 + a 32 x 2 + a 33 x 3 + * * * + a 3 nxn = b 3 .. . am 1 x 1 + am 2 x 2 + am 3 x 3 + * * * + amnxn = bm \nthe coefficient matrix is the m x n matrix \n A = \n       a 11 a 12 a 13... a 1 n a 21 a 22 a 23... a 2 n a 31 a 32 a 33... a 3 n .. . am 1 am 2 am 3... amn \n       \x03 \nDefinition VOC Vector of Constants For a system of linear equations, \n a 11 x 1 + a 12 x 2 + a 13 x 3 + * * * + a 1 nxn = b 1 a 21 x 1 + a 22 x 2 + a 23 x 3 + * * * + a 2 nxn = b 2 a 31 x 1 + a 32 x 2 + a 33 x 3 + * * * + a 3 nxn = b 3 .. . am 1 x 1 + am 2 x 2 + am 3 x 3 + * * * + amnxn = bm \nthe vector of constants is the column vector of size m \n b = \n       b 1 b 2 b 3 .. . bm \n       \x03 \nDefinition SOLV Solution Vector For a system of linear equations, \n a 11 x 1 + a 12 x 2 + a 13 x 3 + * * * + a 1 nxn = b 1 a 21 x 1 + a 22 x 2 + a 23 x 3 + * * * + a 2 nxn = b 2 a 31 x 1 + a 32 x 2 + a 33 x 3 + * * * + a 3 nxn = b 3 \nSSR R E F B e e z e r : A F i r s t C o u r s e i n L i n e a r A l g e b r a 20 \n .. . am 1 x 1 + am 2 x 2 + am 3 x 3 + * * * + amnxn = bm \nthe solution vector is the column vector of size n \n x = \n       x 1 x 2 x 3 .. . xn \n       \x03 \nThe solution vector may do double-duty on occasion. It might refer to a list of variable quantities at one point, and subsequently refer to values of those variables that actually form a particular solution to that system. \nDefinition MRLS Matrix Representation of a Linear System If A is the coefficient matrix of a system of linear equations and b is the vector of constants, then we will write LS(A, b) as a shorthand expression for the system of linear equations, which we will refer to as the matrix representation of the linear system. \x03 \nExample NSLE Notation for systems of linear equations The system of linear equations \n 2 x 1 + 4x 2 - 3 x 3 + 5x 4 + x 5 = 9 3 x 1 + x 2 + x 4 - 3 x 5 = 0 - 2 x 1 + 7x 2 - 5 x 3 + 2 </passage>'},
  {'from': 'gpt',
   'value': '<tool_call>\\n{"arguments": {"queries": [\'How is a matrix defined and what is its purpose in linear algebra?\', \'What is the difference between a coefficient matrix and a vector of constants in a system of equations?\', \'How is a system of equations represented in matrix notation?\'], "name": "ExpertQAExtractor"}}\\n</tool_call>'}],
 'tools': [{'type': 'function',
   'function': {'name': 'ExpertQAExtractor',
    'description': 'Extracts a list of questions that focus on summarizing a specific topic found in the document.',
    'parameters': {'type': 'object',
     'properties': {'topic_summarization_questions': {'type': 'array',
       'items': {'type': 'string'}}},
     'required': ['topic_summarization_questions']}}}],
 'category': 'Information Extraction',
 'subcategory': 'Json Schema',
 'task': 'Structured json schema extaction with function calling',
 'messages': [{'role': 'system',
   'content': "You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema."},
  {'role': 'user',

In [135]:
messages = example['messages']
system_prompt = example['messages'][0]['content']
system_prompt += f'\n\n<tools>\n{json.dumps(example["tools"])}\n</tools>'
print(system_prompt)

You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema.

<tools>
[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of questions that focus on summarizing a specific topic found in the document.", "parameters": {"type": "object", "properties": {"topic_summarization_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["topic_summarization_questions"]}}}]
</tools>

In [139]:
CONVERSATION_HISTORY = []
for msg in messages[1:-1]:  # ignore system prompt and final assistant response
    if msg['role'] == 'user' or msg['role'] == 'tool':
        CONVERSATION_HISTORY.append(f'{msg["role"]}: {msg["content"]}')
    if msg['role'] == 'assistant':
        s = f'{msg["role"]}: {msg["content"]}'
        if 'tool_calls' in msg:
            s += f'\n<tool_calls>\n{json.dumps(msg["tool_calls"])}\n</tool_calls>'
        CONVERSATION_HISTORY.append(s)

print('\n---\n'.join(CONVERSATION_HISTORY))

user: Can you help me extract queries from the following passage <passage> = - 3 x + y - z = 0
C50+^ A three-digit number has two properties. The tens-digit and the ones-digit add up to 5. If the number is written with the digits in the reverse order, and then subtracted
SSS S L E B e e z e r : A F i r s t C o u r s e i n L i n e a r A l g e b r a 16
from the original number, the result is 792. Use a system of equations to find all of the three-digit numbers with these properties.
C51+^ Find all of the six-digit numbers in which the first digit is one less than the second, the third digit is half the second, the fourth digit is three times the third and the last two digits form a number that equals the sum of the fourth and fifth. The sum of all the digits is 24. (From The MENSA Puzzle Calendar for January 9, 2006.)
C52+^ Driving along, Terry notices that the last four digits on his car's odometer are palindromic. A mile later, the last five digits are palindromic. After driving another mile, the middle four digits are palindromic. One more mile, and all six are palindromic. What was the odometer reading when Terry first looked at it? Form a linear system of equations that expresses the requirements of this puzzle. (Car Talk Puzzler, National Public Radio, Week of January 21, 2008) (A car odometer displays six digits and a sequence is a palindrome if it reads the same left-to-right as right-to-left.) M10+^ Each sentence below has at least two meanings. Identify the source of the double meaning, and rewrite the sentence (at least twice) to clearly convey each meaning.
1. They are baking potatoes.
2. He bought many ripe pears and apricots.
3. She likes his sculpture.
4. I decided on the bus.
M11+^ Discuss the difference in meaning of each of the following three almost identical sentences, which all have the same grammatical structure. (These are due to Keith Devlin.)
1. She saw him in the park with a dog.
2. She saw him in the park with a fountain.
3. She saw him in the park with a telescope.
M12+^ The following sentence, due to Noam Chomsky, has a correct grammatical structure, but is meaningless. Critique its faults. "Colorless green ideas sleep furiously." (Chomsky, Noam. Syntactic Structures, The Hague/Paris: Mouton, 1957. p. 15.)
M13+^ Read the following sentence and form a mental picture of the situation. The baby cried and the mother picked it up. What assumptions did you make about the situation?
M14 Discuss the difference in meaning of the following two almost identical sentences, which have nearly identical grammatical structure. (This antanaclasis is often attributed to the comedian Groucho Marx, but has earlier roots.)
1. Time flies like an arrow.
2. Fruit flies like a banana.
M30+^ This problem appears in a middle-school mathematics textbook: Together Dan and Diane have $20. Together Diane and Donna have $15. How much do the three of them have in total? (Transition Mathematics, Second Edition, Scott Foresman Addison Wesley,
1998. Problem 5-1.19.)
M40 Solutions to the system in Example IS are given as
 (x 1 , x 2 , x 3 , x 4 ) = (- 1 - 2 a + 3b, 4 + a - 2 b, a, b)
Evaluate the three equations of the original system with these expressions in a and b and verify that each equation is true, no matter what values are chosen for a and b.
M70+^ We have seen in this section that systems of linear equations have limited possibilities for solution sets, and we will shortly prove Theorem PSSLS that describes these
SSS S L E B e e z e r : A F i r s t C o u r s e i n L i n e a r A l g e b r a 17
possibilities exactly. This exercise will show that if we relax the requirement that our equations be linear, then the possibilities expand greatly. Consider a system of two equations in the two variables x and y, where the departure from linearity involves simply squaring the variables.
 x^2 - y^2 = 1 x^2 + y^2 = 4
After solving this system of nonlinear equations, replace the second equation in turn by x^2 + 2x + y^2 = 3, x^2 + y^2 = 1, x^2 - 4 x + y^2 = -3, -x^2 + y^2 = 1 and solve each resulting system of two equations in two variables. (This exercise includes suggestions from Don Kreher.)
T10+^ Proof Technique D asks you to formulate a definition of what it means for a whole number to be odd. What is your definition? (Do not say "the opposite of even.") Is 6 odd? Is 11 odd? Justify your answers by using your definition. T20+^ Explain why the second equation operation in Definition EO requires that the scalar be nonzero, while in the third equation operation this restriction on the scalar is not present.
### Section RREF
### Reduced Row-Echelon Form
 After solving a few systems of equations, you will recognize that it does not matter so much what we call our variables, as opposed to what numbers act as their coefficients. A system in the variables x 1 , x 2 , x 3 would behave the same if we changed the names of the variables to a, b, c and kept all the constants the same and in the same places. In this section, we will isolate the key bits of information about a system of equations into something called a matrix, and then use this matrix to systematically solve the equations. Along the way we will obtain one of our most important and useful computational tools.
##### Subsection MVNSE
##### Matrix and Vector Notation for Systems of Equations
Definition M Matrix An m x n matrix is a rectangular layout of numbers from C having m rows and n columns. We will use upper-case Latin letters from the start of the alphabet (A, B, C,... ) to denote matrices and squared-off brackets to delimit the layout. Many use large parentheses instead of brackets -- the distinction is not important. Rows of a matrix will be referenced starting at the top and working down (i.e. row 1 is at the top) and columns will be referenced starting from the left (i.e. column 1 is at the left). For a matrix A, the notation [A]ij will refer to the complex number in row i and column j of A.  Be careful with this notation for individual entries, since it is easy to think that [A]ij refers to the whole matrix. It does not. It is just a number, but is a convenient way to talk about the individual entries simultaneously. This notation will get a heavy workout once we get to Chapter M. Example AM A matrix
 B =
 [- 1 2 5 3 1 0 - 6 1 - 4 2 2 - 2
 ]
 is a matrix with m = 3 rows and n = 4 columns. We can say that [B] 2 , 3 = -6 while [B] 3 , 4 = -2. 4 When we do equation operations on system of equations, the names of the variables really are not very important. Use x 1 , x 2 , x 3 , or a, b, c, or x, y, z, it really does not matter. In this subsection we will describe some notation that will make it easier to describe linear systems, solve the systems and describe the solution sets. Here is a list of definitions, laden with notation. Definition CV Column Vector A column vector of size m is an ordered list of m numbers, which is written in order vertically, starting at the top and proceeding to the bottom. At times, we will refer to a column vector as simply a vector. Column vectors will be written in bold, usually with lower case Latin letter from the end of the alphabet such as u, v, w, x, y, z. Some books like to write vectors with arrows, such as ~u. Writing by hand, some like to put arrows on top of the symbol, or a tilde underneath the symbol, as in u ~
. To refer to the entry or component of vector v in location i of the list, we write [v]i.  Be careful with this notation. While the symbols [v]i might look somewhat substantial, as an object this represents just one entry of a vector, which is just a
SSR R E F B e e z e r : A F i r s t C o u r s e i n L i n e a r A l g e b r a 19
single complex number.
Definition ZCV Zero Column Vector The zero vector of size m is the column vector of size m where each entry is the number zero,
 0 =
       0 0 0 .. . 0

or defined much more compactly, [ 0 ]i = 0 for 1 <= i <= m. 
Definition CM Coefficient Matrix For a system of linear equations,
 a 11 x 1 + a 12 x 2 + a 13 x 3 + * * * + a 1 nxn = b 1 a 21 x 1 + a 22 x 2 + a 23 x 3 + * * * + a 2 nxn = b 2 a 31 x 1 + a 32 x 2 + a 33 x 3 + * * * + a 3 nxn = b 3 .. . am 1 x 1 + am 2 x 2 + am 3 x 3 + * * * + amnxn = bm
the coefficient matrix is the m x n matrix
 A =
       a 11 a 12 a 13... a 1 n a 21 a 22 a 23... a 2 n a 31 a 32 a 33... a 3 n .. . am 1 am 2 am 3... amn
       
Definition VOC Vector of Constants For a system of linear equations,
 a 11 x 1 + a 12 x 2 + a 13 x 3 + * * * + a 1 nxn = b 1 a 21 x 1 + a 22 x 2 + a 23 x 3 + * * * + a 2 nxn = b 2 a 31 x 1 + a 32 x 2 + a 33 x 3 + * * * + a 3 nxn = b 3 .. . am 1 x 1 + am 2 x 2 + am 3 x 3 + * * * + amnxn = bm
the vector of constants is the column vector of size m
 b =
       b 1 b 2 b 3 .. . bm
       
Definition SOLV Solution Vector For a system of linear equations,
 a 11 x 1 + a 12 x 2 + a 13 x 3 + * * * + a 1 nxn = b 1 a 21 x 1 + a 22 x 2 + a 23 x 3 + * * * + a 2 nxn = b 2 a 31 x 1 + a 32 x 2 + a 33 x 3 + * * * + a 3 nxn = b 3
SSR R E F B e e z e r : A F i r s t C o u r s e i n L i n e a r A l g e b r a 20
 .. . am 1 x 1 + am 2 x 2 + am 3 x 3 + * * * + amnxn = bm
the solution vector is the column vector of size n
 x =
       x 1 x 2 x 3 .. . xn
       
The solution vector may do double-duty on occasion. It might refer to a list of variable quantities at one point, and subsequently refer to values of those variables that actually form a particular solution to that system.
Definition MRLS Matrix Representation of a Linear System If A is the coefficient matrix of a system of linear equations and b is the vector of constants, then we will write LS(A, b) as a shorthand expression for the system of linear equations, which we will refer to as the matrix representation of the linear system. 
Example NSLE Notation for systems of linear equations The system of linear equations
 2 x 1 + 4x 2 - 3 x 3 + 5x 4 + x 5 = 9 3 x 1 + x 2 + x 4 - 3 x 5 = 0 - 2 x 1 + 7x 2 - 5 x 3 + 2 </passage>

In [143]:
assistant_content_to_corrupt = messages[-1].get('content', None)
assistant_tool_calls_to_corrupt = messages[-1].get('tool_calls', None)

print(assistant_content_to_corrupt)
print(assistant_tool_calls_to_corrupt)

<tool_call>\n{"arguments": {"queries": ['How is a matrix defined and what is its purpose in linear algebra?', 'What is the difference between a coefficient matrix and a vector of constants in a system of equations?', 'How is a system of equations represented in matrix notation?'], "name": "ExpertQAExtractor"}}\n</tool_call>
None

In [149]:
prompt = f"""system_prompt:
{system_prompt}

conversation:
{CONVERSATION_HISTORY}

gold_assistant_response:
{assistant_content_to_corrupt}
"""

corruption_prompt = f"""
{CORRUPTION_PROMPT_BASE}

{CORRUPTION_SYSTEM_PROMPTS['corrupt_tool_call_name']}
Response format:
{CORRUPTION_PROMPT_RESPONSE_FORMAT}
"""
print(corruption_prompt)
print('\n---\n')
print(prompt)

You are generating a deliberately corrupted assistant draft for adapter-training.
You will receive:
- the original system prompt with tool definitions if any
- the original conversation between the user and the assistant
- the gold assistant response

Rewrite the given tool call with a wrong tool name.
Response format:

<corruption_output>
    <notes>[...]</notes>
    <content>if corrupted content</content>
    <tool_calls>if corrupted tool call</tool_calls>
</corruption_output>



---

system_prompt:
You are an expert structured information extraction AI model. You will be provided with documents to extract information from. You are also provided with the json schema to output extracted information in the function signatures within XML tags <tools></tools>. Don't make assumptions about what values to plug into json schema.

<tools>
[{"type": "function", "function": {"name": "ExpertQAExtractor", "description": "Extracts a list of questions that focus on summarizing a specific topic found in the document.", "parameters": {"type": "object", "properties": {"topic_summarization_questions": {"type": "array", "items": {"type": "string"}}}, "required": ["topic_summarization_questions"]}}}]
</tools>

conversation:
['user: Can you help me extract queries from the following passage <passage> = - 3 x + y - z = 0 \nC50+^ A three-digit number has two properties. The tens-digit and the ones-digit add up to 5. If the number is written with the digits in the reverse order, and then subtracted \nSSS S L E B e e z e r : A F i r s t C o u r s e i n L i n e a r A l g e b r a 16 \nfrom the original number, the result is 792. Use a system of equations to find all of the three-digit numbers with these properties. \nC51+^ Find all of the six-digit numbers in which the first digit is one less than the second, the third digit is half the second, the fourth digit is three times the third and the last two digits form a number that equals the sum of the fourth and fifth. The sum of all the digits is 24. (From The MENSA Puzzle Calendar for January 9, 2006.) \nC52+^ Driving along, Terry notices that the last four digits on his car\'s odometer are palindromic. A mile later, the last five digits are palindromic. After driving another mile, the middle four digits are palindromic. One more mile, and all six are palindromic. What was the odometer reading when Terry first looked at it? Form a linear system of equations that expresses the requirements of this puzzle. (Car Talk Puzzler, National Public Radio, Week of January 21, 2008) (A car odometer displays six digits and a sequence is a palindrome if it reads the same left-to-right as right-to-left.) M10+^ Each sentence below has at least two meanings. Identify the source of the double meaning, and rewrite the sentence (at least twice) to clearly convey each meaning. \n1. They are baking potatoes. \n2. He bought many ripe pears and apricots. \n3. She likes his sculpture. \n4. I decided on the bus. \nM11+^ Discuss the difference in meaning of each of the following three almost identical sentences, which all have the same grammatical structure. (These are due to Keith Devlin.) \n1. She saw him in the park with a dog. \n2. She saw him in the park with a fountain. \n3. She saw him in the park with a telescope. \nM12+^ The following sentence, due to Noam Chomsky, has a correct grammatical structure, but is meaningless. Critique its faults. "Colorless green ideas sleep furiously." (Chomsky, Noam. Syntactic Structures, The Hague/Paris: Mouton, 1957. p. 15.) \nM13+^ Read the following sentence and form a mental picture of the situation. The baby cried and the mother picked it up. What assumptions did you make about the situation? \nM14 Discuss the difference in meaning of the following two almost identical sentences, which have nearly identical grammatical structure. (This antanaclasis is often attributed to the comedian Groucho Marx, but has earlier roots.) \n1. Time flies like an arrow. \n2. Fruit flies like a banana. \nM30+^ This problem appears in a middle-school mathematics textbook: Together Dan and Diane have $20. Together Diane and Donna have $15. How much do the three of them have in total? (Transition Mathematics, Second Edition, Scott Foresman Addison Wesley, \n1998. Problem 5-1.19.) \nM40 Solutions to the system in Example IS are given as \n (x 1 , x 2 , x 3 , x 4 ) = (- 1 - 2 a + 3b, 4 + a - 2 b, a, b) \nEvaluate the three equations of the original system with these expressions in a and b and verify that each equation is true, no matter what values are chosen for a and b. \nM70+^ We have seen in this section that systems of linear equations have limited possibilities for solution sets, and we will shortly prove Theorem PSSLS that describes these \nSSS S L E B e e z e r : A F i r s t C o u r s e i n L i n e a r A l g e b r a 17 \npossibilities exactly. This exercise will show that if we relax the requirement that our equations be linear, then the possibilities expand greatly. Consider a system of two equations in the two variables x and y, where the departure from linearity involves simply squaring the variables. \n x^2 - y^2 = 1 x^2 + y^2 = 4 \nAfter solving this system of nonlinear equations, replace the second equation in turn by x^2 + 2x + y^2 = 3, x^2 + y^2 = 1, x^2 - 4 x + y^2 = -3, -x^2 + y^2 = 1 and solve each resulting system of two equations in two variables. (This exercise includes suggestions from Don Kreher.) \nT10+^ Proof Technique D asks you to formulate a definition of what it means for a whole number to be odd. What is your definition? (Do not say "the opposite of even.") Is 6 odd? Is 11 odd? Justify your answers by using your definition. T20+^ Explain why the second equation operation in Definition EO requires that the scalar be nonzero, while in the third equation operation this restriction on the scalar is not present. \n### Section RREF \n### Reduced Row-Echelon Form \n After solving a few systems of equations, you will recognize that it does not matter so much what we call our variables, as opposed to what numbers act as their coefficients. A system in the variables x 1 , x 2 , x 3 would behave the same if we changed the names of the variables to a, b, c and kept all the constants the same and in the same places. In this section, we will isolate the key bits of information about a system of equations into something called a matrix, and then use this matrix to systematically solve the equations. Along the way we will obtain one of our most important and useful computational tools. \n##### Subsection MVNSE \n##### Matrix and Vector Notation for Systems of Equations \nDefinition M Matrix An m x n matrix is a rectangular layout of numbers from C having m rows and n columns. We will use upper-case Latin letters from the start of the alphabet (A, B, C,... ) to denote matrices and squared-off brackets to delimit the layout. Many use large parentheses instead of brackets -- the distinction is not important. Rows of a matrix will be referenced starting at the top and working down (i.e. row 1 is at the top) and columns will be referenced starting from the left (i.e. column 1 is at the left). For a matrix A, the notation [A]ij will refer to the complex number in row i and column j of A. \x03 Be careful with this notation for individual entries, since it is easy to think that [A]ij refers to the whole matrix. It does not. It is just a number, but is a convenient way to talk about the individual entries simultaneously. This notation will get a heavy workout once we get to Chapter M. Example AM A matrix \n B = \n [- 1 2 5 3 1 0 - 6 1 - 4 2 2 - 2 \n ] \n is a matrix with m = 3 rows and n = 4 columns. We can say that [B] 2 , 3 = -6 while [B] 3 , 4 = -2. 4 When we do equation operations on system of equations, the names of the variables really are not very important. Use x 1 , x 2 , x 3 , or a, b, c, or x, y, z, it really does not matter. In this subsection we will describe some notation that will make it easier to describe linear systems, solve the systems and describe the solution sets. Here is a list of definitions, laden with notation. Definition CV Column Vector A column vector of size m is an ordered list of m numbers, which is written in order vertically, starting at the top and proceeding to the bottom. At times, we will refer to a column vector as simply a vector. Column vectors will be written in bold, usually with lower case Latin letter from the end of the alphabet such as u, v, w, x, y, z. Some books like to write vectors with arrows, such as ~u. Writing by hand, some like to put arrows on top of the symbol, or a tilde underneath the symbol, as in u ~ \n. To refer to the entry or component of vector v in location i of the list, we write [v]i. \x03 Be careful with this notation. While the symbols [v]i might look somewhat substantial, as an object this represents just one entry of a vector, which is just a \nSSR R E F B e e z e r : A F i r s t C o u r s e i n L i n e a r A l g e b r a 19 \nsingle complex number. \nDefinition ZCV Zero Column Vector The zero vector of size m is the column vector of size m where each entry is the number zero, \n 0 = \n       0 0 0 .. . 0 \n       \nor defined much more compactly, [ 0 ]i = 0 for 1 <= i <= m. \x03 \nDefinition CM Coefficient Matrix For a system of linear equations, \n a 11 x 1 + a 12 x 2 + a 13 x 3 + * * * + a 1 nxn = b 1 a 21 x 1 + a 22 x 2 + a 23 x 3 + * * * + a 2 nxn = b 2 a 31 x 1 + a 32 x 2 + a 33 x 3 + * * * + a 3 nxn = b 3 .. . am 1 x 1 + am 2 x 2 + am 3 x 3 + * * * + amnxn = bm \nthe coefficient matrix is the m x n matrix \n A = \n       a 11 a 12 a 13... a 1 n a 21 a 22 a 23... a 2 n a 31 a 32 a 33... a 3 n .. . am 1 am 2 am 3... amn \n       \x03 \nDefinition VOC Vector of Constants For a system of linear equations, \n a 11 x 1 + a 12 x 2 + a 13 x 3 + * * * + a 1 nxn = b 1 a 21 x 1 + a 22 x 2 + a 23 x 3 + * * * + a 2 nxn = b 2 a 31 x 1 + a 32 x 2 + a 33 x 3 + * * * + a 3 nxn = b 3 .. . am 1 x 1 + am 2 x 2 + am 3 x 3 + * * * + amnxn = bm \nthe vector of constants is the column vector of size m \n b = \n       b 1 b 2 b 3 .. . bm \n       \x03 \nDefinition SOLV Solution Vector For a system of linear equations, \n a 11 x 1 + a 12 x 2 + a 13 x 3 + * * * + a 1 nxn = b 1 a 21 x 1 + a 22 x 2 + a 23 x 3 + * * * + a 2 nxn = b 2 a 31 x 1 + a 32 x 2 + a 33 x 3 + * * * + a 3 nxn = b 3 \nSSR R E F B e e z e r : A F i r s t C o u r s e i n L i n e a r A l g e b r a 20 \n .. . am 1 x 1 + am 2 x 2 + am 3 x 3 + * * * + amnxn = bm \nthe solution vector is the column vector of size n \n x = \n       x 1 x 2 x 3 .. . xn \n       \x03 \nThe solution vector may do double-duty on occasion. It might refer to a list of variable quantities at one point, and subsequently refer to values of those variables that actually form a particular solution to that system. \nDefinition MRLS Matrix Representation of a Linear System If A is the coefficient matrix of a system of linear equations and b is the vector of constants, then we will write LS(A, b) as a shorthand expression for the system of linear equations, which we will refer to as the matrix representation of the linear system. \x03 \nExample NSLE Notation for systems of linear equations The system of linear equations \n 2 x 1 + 4x 2 - 3 x 3 + 5x 4 + x 5 = 9 3 x 1 + x 2 + x 4 - 3 x 5 = 0 - 2 x 1 + 7x 2 - 5 x 3 + 2 </passage>']

gold_assistant_response:
<tool_call>\n{"arguments": {"queries": ['How is a matrix defined and what is its purpose in linear algebra?', 'What is the difference between a coefficient matrix and a vector of constants in a system of equations?', 'How is a system of equations represented in matrix notation?'], "name": "ExpertQAExtractor"}}\n</tool_call>

In [ ]:
response = client.chat.completions.create(
    model='zai-org/GLM-4.7',
    messages=[
        {"role": "system", "content": corruption_prompt},
        {"role": "user", "content": prompt}
    ],
    max_tokens=32672,
)
print('corruption response:')
print(response.choices[0].message.content)

In [152]:
response.choices[0].finish_reason

'length'

In [ ]:
from __future__ import annotations

from typing import Literal, Any
from pydantic import BaseModel, ConfigDict, Field


CorruptionType = Literal[
    "delete_content",
    "corrupt_content",
    "add_unnecessary_content",
    "delete_tool_call",
    "corrupt_tool_call_name",
    "corrupt_tool_call_argument",
    "add_extra_tool_call",
]


class CorruptedToolFunction(BaseModel):
    model_config = ConfigDict(extra="forbid")

    name: str
    arguments: str  # must stay a JSON-serialized string


class CorruptedToolCall(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str
    type: Literal["function"]
    function: CorruptedToolFunction


class CorruptionOutput(BaseModel):
    model_config = ConfigDict(extra="forbid")

    corruption_type: CorruptionType
    content: str
    tool_calls: list[CorruptedToolCall] = Field(default_factory=list)
    changed_tool_call_indices: list[int] = Field(default_factory=list)
    notes: str


CORRUPTION_RESPONSE_FORMAT = {
    "type": "json_schema",
    "json_schema": {
        "name": "corruption_output",
        "strict": True,
        "schema": {
            "type": "object",
            "additionalProperties": False,
            "properties": {
                "corruption_type": {
                    "type": "string",
                    "enum": [
                        "delete_content",
                        "corrupt_content",
                        "add_unnecessary_content",
                        "delete_tool_call",
                        "corrupt_tool_call_name",
                        "corrupt_tool_call_argument",
                        "add_extra_tool_call",
                    ],
                },
                "content": {"type": "string"},
                "tool_calls": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": False,
                        "properties": {
                            "id": {"type": "string"},
                            "type": {"type": "string", "enum": ["function"]},
                            "function": {
                                "type": "object",
                                "additionalProperties": False,
                                "properties": {
                                    "name": {"type": "string"},
                                    "arguments": {"type": "string"},
                                },
                                "required": ["name", "arguments"],
                            },
                        },
                        "required": ["id", "type", "function"],
                    },
                },
                "changed_tool_call_indices": {
                    "type": "array",
                    "items": {"type": "integer", "minimum": 0},
                },
                "notes": {"type": "string"},
            },
            "required": [
                "corruption_type",
                "content",
                "tool_calls",
                "changed_tool_call_indices",
                "notes",
            ],
        },
    },
}


CORRUPTION_PROMPT_BASE = """
You are generating a deliberately corrupted assistant draft for adapter-training.

You will receive:
- the original conversation
- the gold assistant response as `content` and `tool_calls`
- the available tool definitions if any
- a target corruption type

Your job is to produce exactly one corrupted draft matching that corruption type.

Global rules:
- Preserve the overall structure of the gold response unless the target corruption requires changing it.
- Apply only the requested corruption type.
- Do not introduce any extra corruption types.
- Keep the response realistic and plausible.
- Return valid JSON only matching the required schema.
- `tool_calls` must stay in OpenAI chat-completions format.
- `function.arguments` must remain a JSON-serialized string.
- If a tool call is not being changed, preserve it exactly.
- If content is not being changed, preserve it exactly.
""".strip()


CORRUPTION_SYSTEM_PROMPTS = {
    "delete_content": CORRUPTION_PROMPT_BASE + """

Target corruption: delete_content

Produce a draft where correct assistant text content has been removed.
Rules:
- Set `content` to an empty string.
- Keep `tool_calls` identical to gold.
- Use this only when gold content is non-empty.
- `changed_tool_call_indices` must be empty.
- `notes` should briefly say that content was deleted.
""",
    "corrupt_content": CORRUPTION_PROMPT_BASE + """

Target corruption: corrupt_content

Produce a draft where the assistant text content is still present but wrong.
Rules:
- Keep `content` non-empty.
- Change only the text content.
- The corrupted text should be plausible but materially different from gold.
- Keep `tool_calls` identical to gold.
- `changed_tool_call_indices` must be empty.
- `notes` should briefly describe how the text was corrupted.
""",
    "add_unnecessary_content": CORRUPTION_PROMPT_BASE + """

Target corruption: add_unnecessary_content

Produce a draft with extra assistant text that should not be there.
Rules:
- Add non-empty `content`.
- Keep `tool_calls` identical to gold.
- Best used when gold content is empty or tool-only.
- The added text should be plausible but unnecessary.
- `changed_tool_call_indices` must be empty.
- `notes` should briefly say unnecessary content was added.
""",
    "delete_tool_call": CORRUPTION_PROMPT_BASE + """

Target corruption: delete_tool_call

Produce a draft where one required tool call has been removed.
Rules:
- Remove exactly one existing tool call.
- Keep remaining tool calls in the same relative order.
- Keep `content` identical to gold.
- Use only when gold has at least one tool call.
- `changed_tool_call_indices` should identify the missing position in the gold ordering.
- `notes` should briefly say which tool call was deleted.
""",
    "corrupt_tool_call_name": CORRUPTION_PROMPT_BASE + """

Target corruption: corrupt_tool_call_name

Produce a draft where exactly one tool call has the wrong function name.
Rules:
- Keep the number of tool calls unchanged.
- Change exactly one `function.name`.
- Do not change that tool call's arguments unless unavoidable.
- Keep `content` identical to gold.
- `changed_tool_call_indices` must contain the modified index.
- `notes` should briefly say the tool name was corrupted.
""",
    "corrupt_tool_call_argument": CORRUPTION_PROMPT_BASE + """

Target corruption: corrupt_tool_call_argument

Produce a draft where exactly one tool call has wrong arguments.
Rules:
- Keep the number of tool calls unchanged.
- Change exactly one `function.arguments` string.
- Keep the arguments syntactically valid JSON serialized as a string.
- Do not change the tool name unless unavoidable.
- Keep `content` identical to gold.
- `changed_tool_call_indices` must contain the modified index.
- `notes` should briefly say the arguments were corrupted.
""",
    "add_extra_tool_call": CORRUPTION_PROMPT_BASE + """

Target corruption: add_extra_tool_call

Produce a draft where one extra tool call has been inserted.
Rules:
- Add exactly one extra tool call.
- The extra tool call should be plausible but not part of the gold answer.
- Preserve all original tool calls exactly.
- Keep `content` identical to gold.
- `changed_tool_call_indices` must contain the inserted index.
- `notes` should briefly say an extra tool call was added.
""",
}